aws emr create-cluster \
    --applications Name=Spark Name=Zeppelin \
    --ec2-attributes '{"InstanceProfile":"EMR_EC2_DefaultRole","SubnetId":"subnet-9a95acdc","EmrManagedSlaveSecurityGroup":"sg-050f146bb97eaa250","EmrManagedMasterSecurityGroup":"sg-054778695d46ae657"}' \
    --service-role EMR_DefaultRole \
    --enable-debugging \
    --release-label emr-5.33.1 \
    --log-uri 's3n://tinysearch/pyspark-logs/' \
    --steps '[{"Args":["spark-submit","--deploy-mode","cluster","s3://tinysearch/code/extract.py"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"command-runner.jar","Properties":"","Name":"Spark application"}]' \
    --name 'TinySearch' \
    --instance-groups '[{"InstanceCount":2,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"m4.large","Name":"Core Instance Group"},{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"MASTER","InstanceType":"m4.large","Name":"Master Instance Group"}]' \
    --configurations '[{"Classification":"spark","Properties":{}}]' \
    --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2
